### ISSUE TITLE
Question: Is there a reference implementation?

### ISSUE THREAD

**Issue by mattmazzola** [apollographql/principled-graphql#14]
Hi, was just reading through the website https://principledgraphql.com/ (Great work!) and as a newcomer to graphql I was wondering if there was a link to a reference implementation or examples of each of the principles.  I was hoping to learn and experiment with some of the patterns by trying to incorporate them into my own hobby projects.

Can close if this isn't the place for questions.

**Comment by debergalis** [comment]
A good suggestion. This isn't the best place for such a discussion though. How about https://spectrum.chat/apollo?
