### ISSUE TITLE
Remove Apollo branding

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/principled-graphql#7]
Per feedback from Matt today at mktg sync:

- Remove Apollo logo from header and footer
- Change footer attribution text to read "Written by Geoff Schmidt and Matt DeBergalis, founders of Apollo" with Apollo linking to apollographql.com

**Comment by trevorblades** [comment]
Fixed by b061a676eaee697e22d72bb8aa80d4e77b4161ec
