### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by peggyrayzis** [apollographql/principled-graphql#9]
Matt reported that the footer on mobile looks a little off:
![image 1](https://user-images.githubusercontent.com/18017067/52640691-0af7bc00-2ea5-11e9-8b42-d686e5ca4df1.png)

My recommendation would be to put "View source code" on its own line for all platforms and put "ApolloGraphQL.com · GraphQL Summit" on the line below it. I think it makes sense to separate both out, since "View source code" doesn't really fit in with the Apollo branded links.

You might also want to revert the padding change that Matt made in 3085309 😬

**Comment by trevorblades** [comment]
Fixed by 2202096f113d008bb6de83708b5b6f2a9e5012ad
